/* Cafe QR offline shell — generated by build/render.py, do not edit. */
var C = "kaldisgoat-da7b76ac43", SHELL = ["./", "", "assets/logo.png"];

self.addEventListener("install", function(e){
  // warm the shell so even a first-visit-then-offline still shows the menu
  e.waitUntil(caches.open(C).then(function(c){
    return c.addAll(SHELL).catch(function(){});
  }).then(function(){ return self.skipWaiting(); }));
});

self.addEventListener("activate", function(e){
  e.waitUntil(caches.keys().then(function(ks){
    return Promise.all(ks.map(function(k){
      // only ever touch this cafe's own caches
      if(k !== C && k.indexOf("kaldisgoat-") === 0) return caches.delete(k);
    }));
  }).then(function(){ return self.clients.claim(); }));
});

// A clone must be taken before the response is handed to the page, or the body
// is already disturbed by the time the cache write runs, and nothing is stored.
function keep(e, req, res){
  if(res && res.ok){
    var copy = res.clone();
    e.waitUntil(caches.open(C).then(function(c){ return c.put(req, copy); }));
  }
  return res;
}

self.addEventListener("fetch", function(e){
  var r = e.request;
  if(r.method !== "GET") return;
  var u = new URL(r.url);
  if(u.origin !== location.origin) return;

  // assets are versioned by the build and marked immutable: cache first
  if(u.pathname.indexOf("/assets/") > -1){
    e.respondWith(caches.match(r).then(function(hit){
      return hit || fetch(r).then(function(res){ return keep(e, r, res); });
    }));
    return;
  }

  // the menu itself is network-first, so a published price change is never stale
  if(r.mode === "navigate" || u.pathname.slice(-1) === "/" || u.pathname.slice(-5) === ".html"){
    e.respondWith(
      fetch(r).then(function(res){ return keep(e, r, res); })
        .catch(function(){
          return caches.match(r).then(function(hit){
            return hit || caches.match("./") || Response.error();
          });
        })
    );
  }
});
